AWSTemplateFormatVersion: 2010-09-09
Description: |-
  AWS Cloudformation Template for RDS
  Copyright 2017 MLiy Contributors
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
Parameters:
  Engine:
    Default: mysql
    Description: The name of the database engine to use.
    Type: String
    AllowedValues:
      - mysql
    ConstraintDescription: Must select a supported DB Engine Type.
  EngineVersion:
    Default: 5.6.39
    Description: The version number of the database engine
    Type: String
  DBInstanceClass:
    Default: db.m4.large
    Description: The database instance type
    Type: String
    AllowedValues:
      - db.m4.large
      - db.m4.xlarge
      - db.m4.2xlarge
      - db.m4.4xlarge
      - db.m4.10xlarge
    ConstraintDescription: must select a supported database instance type.
  AllocatedStorage:
    Default: '20'
    Description: The size of the database (Gb)
    Type: Number
    MinValue: '5'
    MaxValue: '1024'
    ConstraintDescription: must be between 5 and 1024Gb.
  StorageType:
    Default: gp2
    Description: RDS Instance Storage Type
    Type: String
    AllowedValues:
      - gp2
      - io1
    ConstraintDescription: Must select a valid DB Storage Type.
  DBName:
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBInstanceId:
    Description: RDS database instance identifier
    Type: String
  Port:
    Default: '3306'
    Description: DB listening port
    Type: Number
  MasterUsername:
    NoEcho: 'true'
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  MasterUserPassword:
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  VPCSecurityGroups:
    Default: ''
    Description: >-
      The list of VPC security groups that contains instances that need access
      to the database
    Type: String
  DBSubnetGroupName:
    Default: ''
    Description: A DB subnet group to associate with the DB instance
    Type: String
  MultiAZ:
    Default: 'true'
    Description: Create a multi-AZ RDS database instance
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    ConstraintDescription: must be either true or false.
  StorageEncrypted:
    Default: 'true'
    Description: Indicates whether the DB instance is encrypted.
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    ConstraintDescription: must be either true or false.
  KmsKeyId:
    Default: ''
    Description: >-
      The ARN of the AWS Key Management Service (AWS KMS) master key that's used
      to encrypt the DB instance.
    Type: String
  PublicAccessibility:
    Default: 'false'
    Description: Indicates whether the DB instance is an internet-facing instance.
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    ConstraintDescription: Must be either true or false.
  CopyTagsToSnapshot:
    Default: 'true'
    Description: >-
      Indicates whether to copy all of the user-defined tags from the DB
      instance to snapshots of the DB instance.
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    ConstraintDescription: Must be either true or false.
  AutoMinorVersionUpgrade:
    Default: 'true'
    Description: >-
      Indicates that minor engine upgrades are applied automatically to the DB
      instance during the maintenance window.
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    ConstraintDescription: Must be either true or false.
  DBParameterGroupName:
    Default: ''
    Description: The name of an existing DB parameter group
    Type: String
  OptionGroupName:
    Default: ''
    Description: The option group that this DB instance is associated with.
    Type: String
Conditions:
  setKmsKeyId:
    'Fn::Not':
      - 'Fn::Equals':
          - Ref: KmsKeyId
          - 'AWS::NoValue'
  setDBParameterGroupName:
    'Fn::Not':
      - 'Fn::Equals':
          - Ref: DBParameterGroupName
          - 'AWS::NoValue'
  setOptionGroupName:
    'Fn::Not':
      - 'Fn::Equals':
          - Ref: OptionGroupName
          - 'AWS::NoValue'
Resources:
  MyDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine:
        Ref: Engine
      EngineVersion:
        Ref: EngineVersion
      DBInstanceClass:
        Ref: DBInstanceClass
      AllocatedStorage:
        Ref: AllocatedStorage
      StorageType:
        Ref: StorageType
      DBName:
        Ref: DBName
      DBInstanceIdentifier: 
        Ref: DBInstanceId
      Port:
        Ref: Port
      MasterUsername:
        Ref: MasterUsername
      MasterUserPassword:
        Ref: MasterUserPassword
      VPCSecurityGroups:
        - Ref: VPCSecurityGroups
      DBSubnetGroupName:
        Ref: DBSubnetGroupName
      MultiAZ:
        Ref: MultiAZ
      StorageEncrypted:
        Ref: StorageEncrypted
      KmsKeyId:
        'Fn::If':
          - setKmsKeyId
          - Ref: KmsKeyId
          - Ref: 'AWS::NoValue'
      PubliclyAccessible:
        Ref: PublicAccessibility
      CopyTagsToSnapshot:
        Ref: CopyTagsToSnapshot
      AutoMinorVersionUpgrade:
        Ref: AutoMinorVersionUpgrade
      DBParameterGroupName:
        'Fn::If':
          - setDBParameterGroupName
          - Ref: DBParameterGroupName
          - Ref: 'AWS::NoValue'
      OptionGroupName:
        'Fn::If':
          - setOptionGroupName
          - Ref: OptionGroupName
          - Ref: 'AWS::NoValue'
      Tags:
        - Key: Name
          Value: RDS Database for MLiy Website
    DeletionPolicy: Delete
Outputs:
  JDBCConnectionString:
    Description: JDBC connection string for database
    Value:
      'Fn::Join':
        - ''
        - - 'jdbc:'
          - Ref: Engine
          - '://'
          - 'Fn::GetAtt':
              - MyDB
              - Endpoint.Address
          - ':'
          - 'Fn::GetAtt':
              - MyDB
              - Endpoint.Port
          - /
          - Ref: DBName
  DBAddress:
    Description: Address of database endpoint
    Value:
      'Fn::GetAtt':
        - MyDB
        - Endpoint.Address
  DBPort:
    Description: Database endpoint port number
    Value:
      'Fn::GetAtt':
        - MyDB
        - Endpoint.Port
